/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jpanelpackage;

import jframepackage.Login_Register;
import classpackage.AdminAccountManager;
import classpackage.ConnectionProvider;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Desktop-Desk
 */
public class forgetPasswordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form forgetPasswordJPanel
     */
    private String query;
    Connection con;
    PreparedStatement pst;
    ResultSet resultSet;
    Border textField_Border = BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(8, 14, 44));

    public forgetPasswordJPanel() {
        initComponents();
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(25, 114, 226));
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
        emailField.setBorder(textField_Border);
        securityQuestionField.setBorder(textField_Border);
        securityAnswerField.setBorder(textField_Border);
        passField.setBorder(textField_Border);
        confirmPassField.setBorder(textField_Border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    AdminAccountManager adminAccountManager = new AdminAccountManager();
    ConnectionProvider connectionProvider = new ConnectionProvider();

    @Override
    public Component add(Component comp) {
        return super.add(comp); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        securityQuestionField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        confirmPassField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchBut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        securityAnswerField = new javax.swing.JTextField();
        saveBut = new javax.swing.JButton();
        movingPanel = new test.PanelRound();
        X_Close = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Forget Password");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        emailField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailField.setForeground(new java.awt.Color(102, 102, 102));
        emailField.setText("example@email.com");
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });

        securityQuestionField.setEditable(false);
        securityQuestionField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        securityQuestionField.setForeground(new java.awt.Color(102, 102, 102));

        passField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passField.setForeground(new java.awt.Color(102, 102, 102));
        passField.setText("password");
        passField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFieldFocusLost(evt);
            }
        });

        confirmPassField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmPassField.setForeground(new java.awt.Color(102, 102, 102));
        confirmPassField.setText("password");
        confirmPassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPassFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPassFieldFocusLost(evt);
            }
        });

        jLabel2.setText("Email");

        jLabel3.setText("Security Question");

        jLabel4.setText("New Password");

        jLabel5.setText("Confirm New Password");

        searchBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchBut.setForeground(new java.awt.Color(102, 102, 102));
        searchBut.setText("Check");
        searchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButActionPerformed(evt);
            }
        });

        jLabel6.setText("Answer");

        securityAnswerField.setEditable(false);
        securityAnswerField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        securityAnswerField.setForeground(new java.awt.Color(102, 102, 102));

        saveBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saveBut.setForeground(new java.awt.Color(102, 102, 102));
        saveBut.setText("Save");
        saveBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(saveBut, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(securityAnswerField)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(securityQuestionField)
                                    .addComponent(passField)
                                    .addComponent(confirmPassField))
                                .addGap(18, 18, 18)
                                .addComponent(searchBut)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(securityQuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(securityAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(saveBut)
                .addGap(48, 48, 48))
        );

        movingPanel.setBackground(new java.awt.Color(25, 114, 226));
        movingPanel.setRoundTopLeft(15);
        movingPanel.setRoundTopRight(15);

        X_Close.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        X_Close.setForeground(new java.awt.Color(255, 255, 255));
        X_Close.setText("X");
        X_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        X_Close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        X_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X_CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout movingPanelLayout = new javax.swing.GroupLayout(movingPanel);
        movingPanel.setLayout(movingPanelLayout);
        movingPanelLayout.setHorizontalGroup(
            movingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(X_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        movingPanelLayout.setVerticalGroup(
            movingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(X_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(movingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButActionPerformed
        // TODO add your handling code here:
        String email, securityQuestion, securityAnswer, password;
        //adminAccountManager.checkValidEmail(emailField, securityQuestionField, securityAnswerField, emailField);
//        adminAccount.setEmail(emailField.getText());
//        adminAccount.setSecurityQuestion(securityQuestionField.getText());
//        adminAccount.setSecurityAnswer(securityAnswerField.getText());
//        adminAccount.setPassword(passField.getText());
        int check = 0;
        query = "SELECT * FROM `user_login` WHERE `email` =?";
        emailField.getText();
        if (emailField.getText().equals(0) || emailField.getText().equals("example@email.com")) {
            check = 1;
            JOptionPane.showMessageDialog(null, "Please Enter your Email");
        } else {
            try {
                con = connectionProvider.getCon();
                pst = con.prepareStatement(query);
                pst.setString(1, emailField.getText());
                resultSet = pst.executeQuery();

                if (resultSet.next()) {
                    check = 1;
                    securityAnswerField.setEditable(true);
                    securityQuestionField.setEditable(false);
                    emailField.setEditable(false);
                    securityQuestionField.setText(resultSet.getString(12));
                    resultSet.close();
                    pst.close();
                }

            } catch (SQLException ex) {
                Logger.getLogger(forgetPasswordJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (check == 0) {
            JOptionPane.showMessageDialog(null, "Incorrect Email");
        }

    }//GEN-LAST:event_searchButActionPerformed

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
        String value = emailField.getText().trim().toLowerCase();
        if (value.equals("example@email.com")) {
            emailField.setText("");
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        String value = emailField.getText().trim().toLowerCase();
        if (value.equals("example@email.com") || value.equals("")) {
            emailField.setText("example@email.com");
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void passFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusGained
        // TODO add your handling code here:
        String value = passField.getText().trim().toLowerCase();
        if (value.equals("password")) {
            passField.setText("");
        }
    }//GEN-LAST:event_passFieldFocusGained

    private void passFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusLost
        // TODO add your handling code here:
        String value = passField.getText().trim().toLowerCase();
        if (value.equals("password") || value.equals("")) {
            passField.setText("password");
        }
    }//GEN-LAST:event_passFieldFocusLost

    private void confirmPassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFieldFocusGained
        // TODO add your handling code here:
        String value = confirmPassField.getText().trim().toLowerCase();
        if (value.equals("password")) {
            confirmPassField.setText("");
        }
    }//GEN-LAST:event_confirmPassFieldFocusGained

    private void confirmPassFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFieldFocusLost
        // TODO add your handling code here:
        String value = confirmPassField.getText().trim().toLowerCase();
        if (value.equals("password") || value.equals("")) {
            confirmPassField.setText("password");
        }
    }//GEN-LAST:event_confirmPassFieldFocusLost

    private void saveButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButActionPerformed
        // TODO add your handling code here:
        if (securityAnswerField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Answer the question");

        } else if (passField.getText().equals("") || passField.getText().equals("password")) {
            JOptionPane.showMessageDialog(null, "Enter the new password");

        } else if (!adminAccountManager.isValidPass(passField.getText())) {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 character including digits and chars");

        } else if (passField.getText().equals(confirmPassField.getText()) == false) {
            JOptionPane.showMessageDialog(this, "The password is not matched!");

        } else {
            adminAccountManager.changePassword(emailField, securityQuestionField, securityAnswerField, passField);
            securityAnswerField.setText("");
            passField.setText("");
            emailField.setText("");
            securityQuestionField.setText("");
            confirmPassField.setText("");
        }
    }//GEN-LAST:event_saveButActionPerformed

    private int x, y;

    public void initMoving(JFrame frame) {
        movingPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                x = me.getX();
                y = me.getY();
            }
        });

        movingPanel.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me) {
                frame.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
            }
        });
    }

    private void X_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X_CloseMouseClicked
        // TODO add your handling code here:
        Login_Register login_Register = new Login_Register();
        login_Register.setVisible(true);
        this.hide();
    }//GEN-LAST:event_X_CloseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X_Close;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private test.PanelRound movingPanel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JButton saveBut;
    private javax.swing.JButton searchBut;
    private javax.swing.JTextField securityAnswerField;
    private javax.swing.JTextField securityQuestionField;
    // End of variables declaration//GEN-END:variables
}
