/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jpanelpackage;

import jframepackage.ForgetPassword;
import classpackage.*;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.*;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import jframepackage.MainDashboard;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.math.BigInteger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Desktop-Desk
 */
public class loginRegisterPanel extends javax.swing.JPanel {

    public static final Pattern VALID_EMAIL_ADDRESS_REGEX = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
    public Matcher matcher;

    /**
     * Creates new form PanelBorder
     */
    public loginRegisterPanel() {
        initComponents();
        setOpaque(false);

        loginB.setBorder(defualt_Top_Border);
        registerB.setBorder(defualt_Top_Border);
        loginBMouseClicked(null);

    }

    private Connection con;
    private PreparedStatement pst;
    private ResultSet resultset, resultSetE;
    private PreparedStatement pste;
    private Border defualt_Top_Border = BorderFactory.createMatteBorder(2, 0, 0, 0, new Color(3, 138, 255));
    private Border red_Top_Border = BorderFactory.createMatteBorder(2, 0, 0, 0, new Color(226, 130, 54));
    private Border textField_Border = BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(8, 14, 44));
    private String query;
    AdminAccountManager adminAccountManager = new AdminAccountManager();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        registerB = new javax.swing.JLabel();
        loginB = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        loginPasswordField = new javax.swing.JPasswordField();
        loginUsernameField = new javax.swing.JTextField();
        loginBut = new javax.swing.JButton();
        uImg = new javax.swing.JLabel();
        pImg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        loginShowPassCB = new javax.swing.JCheckBox();
        forgotPass = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        registerUsernameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registerPasswordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        confirmPassField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        registerSecurityQuestionComboBox = new javax.swing.JComboBox<>();
        pImg1 = new javax.swing.JLabel();
        uImg1 = new javax.swing.JLabel();
        pImg2 = new javax.swing.JLabel();
        registerBut = new javax.swing.JButton();
        registerShowPassCB = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        registerEmailField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        registerAnswerField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        registerAddress = new javax.swing.JTextField();
        registerFirstNameField = new javax.swing.JTextField();
        registerLastNameTextField = new javax.swing.JTextField();
        registerPhoneNumberTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        registerNationalityTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        registerIdentityIDTextField = new javax.swing.JTextField();
        registerIdentityCardOptionComboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        movingPanel = new javax.swing.JPanel();
        X_Close = new javax.swing.JLabel();

        setBackground(new java.awt.Color(25, 114, 226));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerB.setBackground(new java.awt.Color(24, 119, 243));
        registerB.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        registerB.setForeground(new java.awt.Color(255, 255, 255));
        registerB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerB.setText("Register");
        registerB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerB.setOpaque(true);
        registerB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBMouseClicked(evt);
            }
        });
        jPanel2.add(registerB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 320, 79));

        loginB.setBackground(new java.awt.Color(24, 119, 243));
        loginB.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginB.setForeground(new java.awt.Color(255, 255, 255));
        loginB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginB.setText("Login");
        loginB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginB.setOpaque(true);
        loginB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBMouseClicked(evt);
            }
        });
        jPanel2.add(loginB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 79));

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));

        loginPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginPasswordField.setForeground(new java.awt.Color(102, 102, 102));
        loginPasswordField.setText("password");
        loginPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginPasswordFieldFocusLost(evt);
            }
        });

        loginUsernameField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginUsernameField.setForeground(new java.awt.Color(102, 102, 102));
        loginUsernameField.setText("example@email.com or username");
        loginUsernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginUsernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginUsernameFieldFocusLost(evt);
            }
        });

        loginBut.setBackground(new java.awt.Color(24, 119, 243));
        loginBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginBut.setForeground(new java.awt.Color(255, 255, 255));
        loginBut.setText("Login");
        loginBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButActionPerformed(evt);
            }
        });

        uImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpanelpackage/IMG/userIMG.png"))); // NOI18N
        uImg.setAlignmentY(0.0F);

        pImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpanelpackage/IMG/passIMG.png"))); // NOI18N
        pImg.setAlignmentY(0.0F);

        jLabel8.setText("Password");

        jLabel9.setText("Email or Username");

        loginShowPassCB.setText("Show password");
        loginShowPassCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginShowPassCBActionPerformed(evt);
            }
        });

        forgotPass.setForeground(new java.awt.Color(102, 102, 102));
        forgotPass.setText("Forgot Password?");
        forgotPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        forgotPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginShowPassCB)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(uImg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pImg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(loginBut, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(forgotPass, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uImg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pImg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(forgotPass)
                .addGap(17, 17, 17)
                .addComponent(loginShowPassCB)
                .addGap(44, 44, 44)
                .addComponent(loginBut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jPanel2.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 630, 650));

        registerPanel.setBackground(new java.awt.Color(255, 255, 255));

        registerUsernameField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerUsernameField.setForeground(new java.awt.Color(102, 102, 102));
        registerUsernameField.setText("username");
        registerUsernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerUsernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerUsernameFieldFocusLost(evt);
            }
        });

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        registerPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerPasswordField.setForeground(new java.awt.Color(102, 102, 102));
        registerPasswordField.setText("password");
        registerPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerPasswordFieldFocusLost(evt);
            }
        });

        jLabel4.setText("Confirm Password");

        confirmPassField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmPassField.setForeground(new java.awt.Color(102, 102, 102));
        confirmPassField.setText("password");
        confirmPassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPassFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPassFieldFocusLost(evt);
            }
        });

        jLabel5.setText("Security Question");

        registerSecurityQuestionComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerSecurityQuestionComboBox.setForeground(new java.awt.Color(102, 102, 102));
        registerSecurityQuestionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Question...", "In what city were you born?", "What is the name of your favorite pet?", "What high school did you attend?", "What was the name of your elementary school?" }));

        pImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpanelpackage/IMG/passIMG.png"))); // NOI18N
        pImg1.setAlignmentY(0.0F);
        pImg1.setPreferredSize(new java.awt.Dimension(30, 30));

        uImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpanelpackage/IMG/userIMG.png"))); // NOI18N
        uImg1.setAlignmentY(0.0F);
        uImg1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpanelpackage/IMG/passIMG.png"))); // NOI18N
        pImg2.setAlignmentY(0.0F);

        registerBut.setBackground(new java.awt.Color(0, 102, 255));
        registerBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerBut.setForeground(new java.awt.Color(255, 255, 255));
        registerBut.setText("Register");
        registerBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButActionPerformed(evt);
            }
        });

        registerShowPassCB.setText("Show password");
        registerShowPassCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerShowPassCBActionPerformed(evt);
            }
        });

        jLabel1.setText("Email");

        registerEmailField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerEmailField.setForeground(new java.awt.Color(102, 102, 102));
        registerEmailField.setText("example@email.com");
        registerEmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerEmailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerEmailFieldFocusLost(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpanelpackage/IMG/email.png"))); // NOI18N

        registerAnswerField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerAnswerField.setForeground(new java.awt.Color(102, 102, 102));
        registerAnswerField.setText("answer");
        registerAnswerField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerAnswerFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerAnswerFieldFocusLost(evt);
            }
        });

        jLabel7.setText("Answer");

        jLabel10.setText("First Name");

        jLabel11.setText("Last Name");

        jLabel12.setText("Address");

        registerAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerAddress.setForeground(new java.awt.Color(102, 102, 102));
        registerAddress.setText("address");
        registerAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerAddressFocusLost(evt);
            }
        });

        registerFirstNameField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerFirstNameField.setForeground(new java.awt.Color(102, 102, 102));
        registerFirstNameField.setText("first name");
        registerFirstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerFirstNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerFirstNameFieldFocusLost(evt);
            }
        });

        registerLastNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerLastNameTextField.setForeground(new java.awt.Color(102, 102, 102));
        registerLastNameTextField.setText("last name");
        registerLastNameTextField.setMaximumSize(null);
        registerLastNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerLastNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerLastNameTextFieldFocusLost(evt);
            }
        });

        registerPhoneNumberTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerPhoneNumberTextField.setForeground(new java.awt.Color(102, 102, 102));
        registerPhoneNumberTextField.setText("85512345678");
        registerPhoneNumberTextField.setCaretColor(new java.awt.Color(102, 102, 102));
        registerPhoneNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerPhoneNumberTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerPhoneNumberTextFieldFocusLost(evt);
            }
        });

        jLabel13.setText("Phone Number");

        registerNationalityTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerNationalityTextField.setForeground(new java.awt.Color(102, 102, 102));
        registerNationalityTextField.setText("nationality");
        registerNationalityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerNationalityTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerNationalityTextFieldFocusLost(evt);
            }
        });

        jLabel14.setText("Nationality");

        registerIdentityIDTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerIdentityIDTextField.setForeground(new java.awt.Color(102, 102, 102));
        registerIdentityIDTextField.setText("123456789");
        registerIdentityIDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerIdentityIDTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerIdentityIDTextFieldFocusLost(evt);
            }
        });

        registerIdentityCardOptionComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerIdentityCardOptionComboBox.setForeground(new java.awt.Color(102, 102, 102));
        registerIdentityCardOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Identity Card...", "National ID", "Passport ID" }));

        jLabel15.setText("National ID or Passport ID");

        jLabel16.setText("Select Identity Card");

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(uImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(registerPanelLayout.createSequentialGroup()
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registerFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(registerLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(registerEmailField)
                            .addComponent(registerUsernameField)))
                    .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerPanelLayout.createSequentialGroup()
                            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(registerIdentityCardOptionComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(registerPanelLayout.createSequentialGroup()
                                    .addGap(94, 94, 94)
                                    .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(registerPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel16))))
                            .addGap(18, 18, 18)
                            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(registerNationalityTextField)
                                    .addComponent(registerIdentityIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pImg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registerSecurityQuestionComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(registerAnswerField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registerAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                    .addComponent(registerShowPassCB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registerBut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(registerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uImg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerUsernameField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerNationalityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerIdentityIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerIdentityCardOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(registerPasswordField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pImg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmPassField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(registerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerSecurityQuestionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(registerAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerShowPassCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerBut, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel6.getAccessibleContext().setAccessibleName("");

        jPanel2.add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 630, -1));

        movingPanel.setBackground(new java.awt.Color(25, 114, 226));

        X_Close.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        X_Close.setForeground(new java.awt.Color(255, 255, 255));
        X_Close.setText("X");
        X_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        X_Close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        X_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X_CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout movingPanelLayout = new javax.swing.GroupLayout(movingPanel);
        movingPanel.setLayout(movingPanelLayout);
        movingPanelLayout.setHorizontalGroup(
            movingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movingPanelLayout.createSequentialGroup()
                .addContainerGap(612, Short.MAX_VALUE)
                .addComponent(X_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        movingPanelLayout.setVerticalGroup(
            movingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(X_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(movingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 763, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void registerBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBMouseClicked
        // TODO add your handling code here:
        registerB.setBorder(red_Top_Border);
        loginB.setBorder(defualt_Top_Border);
        registerB.setBackground(Color.WHITE);
        registerB.setForeground(Color.BLACK);
        loginB.setBackground(new Color(3, 138, 255));
        loginB.setForeground(Color.WHITE);
        registerUsernameField.setBorder(textField_Border);
        registerPasswordField.setBorder(textField_Border);
        confirmPassField.setBorder(textField_Border);
        registerEmailField.setBorder(textField_Border);
        registerAnswerField.setBorder(textField_Border);
        registerAddress.setBorder(textField_Border);
        registerPhoneNumberTextField.setBorder(textField_Border);
        registerFirstNameField.setBorder(textField_Border);
        registerLastNameTextField.setBorder(textField_Border);
        registerNationalityTextField.setBorder(textField_Border);
        registerIdentityIDTextField.setBorder(textField_Border);
        registerPanel.setVisible(true);
        loginPanel.setVisible(false);
    }//GEN-LAST:event_registerBMouseClicked

    private void loginBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBMouseClicked
        // TODO add your handling code here:
        loginB.setBorder(red_Top_Border);
        registerB.setBorder(defualt_Top_Border);
        loginB.setBackground(Color.WHITE);
        loginB.setForeground(Color.BLACK);
        registerB.setBackground(new Color(3, 138, 255));
        registerB.setForeground(Color.WHITE);
        loginUsernameField.setBorder(textField_Border);
        loginPasswordField.setBorder(textField_Border);
        loginPanel.setVisible(true);
        registerPanel.setVisible(false);
    }//GEN-LAST:event_loginBMouseClicked

    private void loginPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPasswordFieldFocusGained
        // TODO add your handling code here:
        String passwordValue = loginPasswordField.getText().trim().toLowerCase();
        if (passwordValue.equals("password")) {
            loginPasswordField.setText("");
        }
    }//GEN-LAST:event_loginPasswordFieldFocusGained

    private void loginPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPasswordFieldFocusLost
        // TODO add your handling code here:
        String passwordValue = loginPasswordField.getText().trim().toLowerCase();
        if (passwordValue.equals("password") || passwordValue.equals("")) {
            loginPasswordField.setText("password");
        }
    }//GEN-LAST:event_loginPasswordFieldFocusLost

    private void loginUsernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUsernameFieldFocusGained
        // TODO add your handling code here:
        String usernameValue = loginUsernameField.getText().trim().toLowerCase();
        if (usernameValue.equals("example@email.com or username")) {
            loginUsernameField.setText("");
        }
    }//GEN-LAST:event_loginUsernameFieldFocusGained

    private void loginUsernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUsernameFieldFocusLost
        // TODO add your handling code here:

        String usernameValue = loginUsernameField.getText().trim().toLowerCase();
        if (usernameValue.equals("example@email.com or username") || usernameValue.equals("")) {
            loginUsernameField.setText("example@email.com or username");
        }
    }//GEN-LAST:event_loginUsernameFieldFocusLost

    private void loginButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButActionPerformed
        String username = loginUsernameField.getText();
        String password = loginPasswordField.getText();
        if (loginUsernameField.getText().isEmpty() || loginUsernameField.getText().equals("example@email.com or username") || loginPasswordField.getPassword().equals("") || loginPasswordField.getPassword().equals("password")) {
            JOptionPane.showMessageDialog(this, "Username or Password Blank");
        } else {
            if (adminAccountManager.login(username, password) == true) {
                this.hide();
                MainDashboard mainDashboard = new MainDashboard();
                mainDashboard.setVisible(true);
            } else if (adminAccountManager.login(username, password) == false) {
                loginPasswordField.setText("");
                loginUsernameField.requestFocus();
                JOptionPane.showMessageDialog(this, "Username, Email or Password is incorrect");
            }
        }
    }//GEN-LAST:event_loginButActionPerformed

    private void X_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_X_CloseMouseClicked

    private void loginShowPassCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginShowPassCBActionPerformed
        // TODO add your handling code here:
        if (loginShowPassCB.isSelected()) {
            loginPasswordField.setEchoChar((char) 0);
        } else {
            loginPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_loginShowPassCBActionPerformed

    private void forgotPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPassMouseClicked
        // TODO add your handling code here:
        ForgetPassword forgetPasswordB = new ForgetPassword();
        this.hide();
        forgetPasswordB.setVisible(true);

    }//GEN-LAST:event_forgotPassMouseClicked

    private void registerAnswerFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerAnswerFieldFocusLost
        // TODO add your handling code here:
        String answerValue = registerAnswerField.getText().trim().toLowerCase();
        if (answerValue.equals("answer") || answerValue.equals("")) {
            registerAnswerField.setText("answer");
        }
    }//GEN-LAST:event_registerAnswerFieldFocusLost

    private void registerAnswerFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerAnswerFieldFocusGained
        // TODO add your handling code here:
        String answerValue = registerAnswerField.getText().trim().toLowerCase();
        if (answerValue.equals("answer")) {
            registerAnswerField.setText("");
        }
    }//GEN-LAST:event_registerAnswerFieldFocusGained

    private void registerEmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerEmailFieldFocusLost
        // TODO add your handling code here:
        String emailValue = registerEmailField.getText().trim().toLowerCase();
        if (emailValue.equals("example@email.com") || emailValue.equals("")) {
            registerEmailField.setText("example@email.com");
        }
    }//GEN-LAST:event_registerEmailFieldFocusLost

    private void registerEmailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerEmailFieldFocusGained
        // TODO add your handling code here:
        String emailValue = registerEmailField.getText().trim().toLowerCase();
        if (emailValue.equals("example@email.com")) {
            registerEmailField.setText("");
        }
    }//GEN-LAST:event_registerEmailFieldFocusGained

    private void registerShowPassCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerShowPassCBActionPerformed
        // TODO add your handling code here:
        if (registerShowPassCB.isSelected()) {
            confirmPassField.setEchoChar((char) 0);
            registerPasswordField.setEchoChar((char) 0);
        } else {
            confirmPassField.setEchoChar('*');
            registerPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_registerShowPassCBActionPerformed

    private void registerButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButActionPerformed
        // TODO add your handling code here:

        //If Else Statement
        matcher = VALID_EMAIL_ADDRESS_REGEX.matcher(registerEmailField.getText());
        if (!matcher.find() || registerEmailField.getText().equals("example@email.com")) {
            JOptionPane.showMessageDialog(this, "Enter your email. 'example@email.com'");
        } else if (registerFirstNameField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter First Name");

        } else if (registerLastNameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Last Name");

        } else if (registerUsernameField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter UserName");

        } else if (registerPhoneNumberTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Phone number");

        } else if (registerNationalityTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Nationality");

        } else if (registerIdentityCardOptionComboBox.getSelectedItem().toString().equals("Select Identity Card...")) {
            JOptionPane.showMessageDialog(this, "Select what type of Identity Card is use");

        } else if (registerIdentityIDTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter your 'National ID' or 'Passport ID'");

        } else if (adminAccountManager.checkNationalID(registerIdentityCardOptionComboBox.getSelectedItem().toString(), registerIdentityIDTextField.getText())) {
            JOptionPane.showMessageDialog(this, "This indentity card and ID is already used");

        } else if (registerPasswordField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Password");

        } else if (registerAddress.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter your address");

        } else if (!adminAccountManager.isValidPass(registerPasswordField.getText())) {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 character including digits and chars");

        } else if (registerPasswordField.getText().equals(confirmPassField.getText()) == false) {
            JOptionPane.showMessageDialog(this, "Password Not Matched");

        } else if (adminAccountManager.checkUsername(registerUsernameField.getText())) {
            JOptionPane.showMessageDialog(null, registerUsernameField.getText() + " This username already exit");

        } else if (adminAccountManager.checkEmail(registerEmailField.getText())) {
            JOptionPane.showMessageDialog(this, registerEmailField.getText() + " already exist");

        } else if (registerSecurityQuestionComboBox.getSelectedItem().equals("Select Question...")) {
            JOptionPane.showMessageDialog(this, "Please select any question and answer");

        } else if (registerAnswerField.getText().length() == 0 || registerAnswerField.getText().equals("answer")) {
            JOptionPane.showMessageDialog(this, "Please answer the question..");

        } else {
            adminAccountManager.register(registerEmailField, registerFirstNameField, registerLastNameTextField,
                    registerUsernameField, registerPhoneNumberTextField, registerNationalityTextField,
                    registerIdentityCardOptionComboBox, registerIdentityIDTextField, confirmPassField,
                    registerAddress, registerSecurityQuestionComboBox, registerAnswerField);

            registerEmailField.setText("");
            registerFirstNameField.setText("");
            registerLastNameTextField.setText("");
            registerUsernameField.setText("");
            registerPhoneNumberTextField.setText("");
            registerNationalityTextField.setText("");
            registerIdentityCardOptionComboBox.setSelectedIndex(0);
            registerIdentityIDTextField.setText("");
            registerPasswordField.setText("");
            confirmPassField.setText("");
            registerAddress.setText("");
            registerSecurityQuestionComboBox.setSelectedIndex(0);
            registerAnswerField.setText("");

        }
    }//GEN-LAST:event_registerButActionPerformed

///////////////////////Text Field Design//////////////////////////////////////////////////////////////
    private void confirmPassFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFieldFocusLost
        // TODO add your handling code here:
        String value = confirmPassField.getText().trim().toLowerCase();
        if (value.equals("password") || value.equals("")) {
            confirmPassField.setText("password");
        }
    }//GEN-LAST:event_confirmPassFieldFocusLost

    private void confirmPassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFieldFocusGained
        // TODO add your handling code here:
        String value = confirmPassField.getText().trim().toLowerCase();
        if (value.equals("password")) {
            confirmPassField.setText("");
        }
    }//GEN-LAST:event_confirmPassFieldFocusGained

    private void registerPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerPasswordFieldFocusLost
        // TODO add your handling code here:
        String value = registerPasswordField.getText().trim().toLowerCase();
        if (value.equals("password") || value.equals("")) {
            registerPasswordField.setText("password");
        }
    }//GEN-LAST:event_registerPasswordFieldFocusLost

    private void registerPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerPasswordFieldFocusGained
        // TODO add your handling code here:
        String value = registerPasswordField.getText().trim().toLowerCase();
        if (value.equals("password")) {
            registerPasswordField.setText("");
        }
    }//GEN-LAST:event_registerPasswordFieldFocusGained

    private void registerUsernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerUsernameFieldFocusLost
        // TODO add your handling code here:
        String value = registerUsernameField.getText().trim().toLowerCase();
        if (value.equals("username") || value.equals("")) {
            registerUsernameField.setText("username");
        }
    }//GEN-LAST:event_registerUsernameFieldFocusLost

    private void registerUsernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerUsernameFieldFocusGained
        // TODO add your handling code here:
        String value = registerUsernameField.getText().trim().toLowerCase();
        if (value.equals("username")) {
            registerUsernameField.setText("");
        }
    }//GEN-LAST:event_registerUsernameFieldFocusGained

    private void registerFirstNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerFirstNameFieldFocusGained
        // TODO add your handling code here:
        String value = registerFirstNameField.getText().trim().toLowerCase();
        if (value.equals("first name")) {
            registerFirstNameField.setText("");
        }
    }//GEN-LAST:event_registerFirstNameFieldFocusGained

    private void registerFirstNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerFirstNameFieldFocusLost
        // TODO add your handling code here:
        String value = registerFirstNameField.getText().trim().toLowerCase();
        if (value.equals("first name") || value.equals("")) {
            registerFirstNameField.setText("first name");
        }
    }//GEN-LAST:event_registerFirstNameFieldFocusLost

    private void registerLastNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerLastNameTextFieldFocusGained
        // TODO add your handling code here:
        String value = registerLastNameTextField.getText().trim().toLowerCase();
        if (value.equals("last name")) {
            registerLastNameTextField.setText("");
        }
    }//GEN-LAST:event_registerLastNameTextFieldFocusGained

    private void registerLastNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerLastNameTextFieldFocusLost
        // TODO add your handling code here:
        String value = registerLastNameTextField.getText().trim().toLowerCase();
        if (value.equals("last name") || value.equals("")) {
            registerLastNameTextField.setText("last name");
        }
    }//GEN-LAST:event_registerLastNameTextFieldFocusLost

    private void registerPhoneNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerPhoneNumberTextFieldFocusGained
        // TODO add your handling code here:
        String value = registerPhoneNumberTextField.getText().trim().toLowerCase();
        if (value.equals("85512345678")) {
            registerPhoneNumberTextField.setText("");
        }
    }//GEN-LAST:event_registerPhoneNumberTextFieldFocusGained

    private void registerPhoneNumberTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerPhoneNumberTextFieldFocusLost
        // TODO add your handling code here:
        String value = registerPhoneNumberTextField.getText().trim().toLowerCase();
        if (value.equals("85512345678") || value.equals("")) {
            registerPhoneNumberTextField.setText("85512345678");
        }
    }//GEN-LAST:event_registerPhoneNumberTextFieldFocusLost

    private void registerNationalityTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerNationalityTextFieldFocusGained
        // TODO add your handling code here:
        String value = registerNationalityTextField.getText().trim().toLowerCase();
        if (value.equals("nationality")) {
            registerNationalityTextField.setText("");
        }
    }//GEN-LAST:event_registerNationalityTextFieldFocusGained

    private void registerNationalityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerNationalityTextFieldFocusLost
        // TODO add your handling code here:
        String value = registerNationalityTextField.getText().trim().toLowerCase();
        if (value.equals("nationality") || value.equals("")) {
            registerNationalityTextField.setText("nationality");
        }
    }//GEN-LAST:event_registerNationalityTextFieldFocusLost

    private void registerIdentityIDTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerIdentityIDTextFieldFocusGained
        // TODO add your handling code here:
        String value = registerIdentityIDTextField.getText().trim().toLowerCase();
        if (value.equals("123456789")) {
            registerIdentityIDTextField.setText("");
        }
    }//GEN-LAST:event_registerIdentityIDTextFieldFocusGained

    private void registerIdentityIDTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerIdentityIDTextFieldFocusLost
        // TODO add your handling code here:
        String value = registerIdentityIDTextField.getText().trim().toLowerCase();
        if (value.equals("123456789") || value.equals("")) {
            registerIdentityIDTextField.setText("123456789");
        }
    }//GEN-LAST:event_registerIdentityIDTextFieldFocusLost

    private void registerAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerAddressFocusGained
        // TODO add your handling code here:
        String value = registerAddress.getText().trim().toLowerCase();
        if (value.equals("address")) {
            registerAddress.setText("");
        }
    }//GEN-LAST:event_registerAddressFocusGained

    private void registerAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerAddressFocusLost
        // TODO add your handling code here:
        String value = registerAddress.getText().trim().toLowerCase();
        if (value.equals("address") || value.equals("")) {
            registerAddress.setText("address");
        }
    }//GEN-LAST:event_registerAddressFocusLost
///////////////////////////////////////////////////////////////////////////////////////////////////////////////

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(25, 114, 226));
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }

    private int x, y;

    public void initMoving(JFrame frame) {
        movingPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                x = me.getX();
                y = me.getY();
            }
        });

        movingPanel.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me) {
                frame.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X_Close;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel forgotPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginB;
    private javax.swing.JButton loginBut;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JCheckBox loginShowPassCB;
    private javax.swing.JTextField loginUsernameField;
    private javax.swing.JPanel movingPanel;
    private javax.swing.JLabel pImg;
    private javax.swing.JLabel pImg1;
    private javax.swing.JLabel pImg2;
    private javax.swing.JTextField registerAddress;
    private javax.swing.JTextField registerAnswerField;
    private javax.swing.JLabel registerB;
    private javax.swing.JButton registerBut;
    private javax.swing.JTextField registerEmailField;
    private javax.swing.JTextField registerFirstNameField;
    private javax.swing.JComboBox<String> registerIdentityCardOptionComboBox;
    private javax.swing.JTextField registerIdentityIDTextField;
    private javax.swing.JTextField registerLastNameTextField;
    private javax.swing.JTextField registerNationalityTextField;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPasswordField registerPasswordField;
    private javax.swing.JTextField registerPhoneNumberTextField;
    private javax.swing.JComboBox<String> registerSecurityQuestionComboBox;
    private javax.swing.JCheckBox registerShowPassCB;
    private javax.swing.JTextField registerUsernameField;
    private javax.swing.JLabel uImg;
    private javax.swing.JLabel uImg1;
    // End of variables declaration//GEN-END:variables
}
