/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jpanelpackage;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.security.interfaces.RSAKey;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import mypackage.Login_Register;
import mypackage.MainDashboard;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Desktop-Desk
 */
public class menuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form menuJPanel
     */
    public menuJPanel() {
        initComponents();
        setOpaque(false);
        homeBut.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new test.PanelRound();
        homeBut = new javax.swing.JLabel();
        customerCheckInBut = new javax.swing.JLabel();
        customerCheckOutBut = new javax.swing.JLabel();
        historyBut = new javax.swing.JLabel();
        manageRoomBut = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(225, 670));
        setPreferredSize(new java.awt.Dimension(225, 670));

        panelRound2.setBackground(new java.awt.Color(102, 153, 255));
        panelRound2.setMaximumSize(new java.awt.Dimension(225, 670));
        panelRound2.setPreferredSize(new java.awt.Dimension(225, 670));
        panelRound2.setRoundBottomLeft(15);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeBut.setBackground(new java.awt.Color(255, 255, 255));
        homeBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homeBut.setText("Home");
        homeBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBut.setOpaque(true);
        homeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButMouseClicked(evt);
            }
        });
        panelRound2.add(homeBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 80, 161, 40));

        customerCheckInBut.setBackground(new java.awt.Color(102, 153, 255));
        customerCheckInBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customerCheckInBut.setForeground(new java.awt.Color(255, 255, 255));
        customerCheckInBut.setText("Customer Check In");
        customerCheckInBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerCheckInBut.setOpaque(true);
        customerCheckInBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerCheckInButMouseClicked(evt);
            }
        });
        panelRound2.add(customerCheckInBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 196, 161, 40));

        customerCheckOutBut.setBackground(new java.awt.Color(102, 153, 255));
        customerCheckOutBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customerCheckOutBut.setForeground(new java.awt.Color(255, 255, 255));
        customerCheckOutBut.setText("Customer Check out");
        customerCheckOutBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerCheckOutBut.setOpaque(true);
        customerCheckOutBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerCheckOutButMouseClicked(evt);
            }
        });
        panelRound2.add(customerCheckOutBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 254, -1, 40));

        historyBut.setBackground(new java.awt.Color(102, 153, 255));
        historyBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        historyBut.setForeground(new java.awt.Color(255, 255, 255));
        historyBut.setText("History");
        historyBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyBut.setOpaque(true);
        historyBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyButMouseClicked(evt);
            }
        });
        panelRound2.add(historyBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 312, 161, 40));

        manageRoomBut.setBackground(new java.awt.Color(102, 153, 255));
        manageRoomBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageRoomBut.setForeground(new java.awt.Color(255, 255, 255));
        manageRoomBut.setText("Manage Room");
        manageRoomBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageRoomBut.setOpaque(true);
        manageRoomBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageRoomButMouseClicked(evt);
            }
        });
        panelRound2.add(manageRoomBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 138, 161, 40));

        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpanelpackage/IMG/account-logout.png"))); // NOI18N
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
        });
        panelRound2.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 600, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setLabelFor(logOut);
        jLabel2.setText("Logout");
        panelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 638, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homeButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButMouseClicked
        // TODO add your handling code here:
        homeBut.setBackground(Color.WHITE);
        customerCheckInBut.setBackground(new Color(102, 153, 255));
        customerCheckOutBut.setBackground(new Color(102, 153, 255));
        historyBut.setBackground(new Color(102, 153, 255));
        homeBut.setForeground(Color.black);
        manageRoomBut.setBackground(new Color(102, 153, 255));
        manageRoomBut.setForeground(Color.WHITE);
        customerCheckInBut.setForeground(Color.WHITE);
        customerCheckOutBut.setForeground(Color.WHITE);
        historyBut.setForeground(Color.WHITE);
    }//GEN-LAST:event_homeButMouseClicked

    private void customerCheckInButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerCheckInButMouseClicked
        // TODO add your handling code here:
        customerCheckInBut.setBackground(Color.WHITE);
        homeBut.setBackground(new Color(102, 153, 255));
        customerCheckOutBut.setBackground(new Color(102, 153, 255));
        historyBut.setBackground(new Color(102, 153, 255));
        customerCheckInBut.setForeground(Color.black);
        homeBut.setForeground(Color.WHITE);
        customerCheckOutBut.setForeground(Color.WHITE);
        historyBut.setForeground(Color.WHITE);
        manageRoomBut.setBackground(new Color(102, 153, 255));
        manageRoomBut.setForeground(Color.WHITE);
    }//GEN-LAST:event_customerCheckInButMouseClicked

    private void customerCheckOutButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerCheckOutButMouseClicked
        // TODO add your handling code here:
        customerCheckOutBut.setBackground(Color.WHITE);
        customerCheckInBut.setBackground(new Color(102, 153, 255));
        homeBut.setBackground(new Color(102, 153, 255));
        historyBut.setBackground(new Color(102, 153, 255));
        customerCheckOutBut.setForeground(Color.black);
        customerCheckInBut.setForeground(Color.WHITE);
        homeBut.setForeground(Color.WHITE);
        historyBut.setForeground(Color.WHITE);
        manageRoomBut.setBackground(new Color(102, 153, 255));
        manageRoomBut.setForeground(Color.WHITE);
    }//GEN-LAST:event_customerCheckOutButMouseClicked

    private void historyButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyButMouseClicked
        // TODO add your handling code here:
        historyBut.setBackground(Color.WHITE);
        customerCheckInBut.setBackground(new Color(102, 153, 255));
        customerCheckOutBut.setBackground(new Color(102, 153, 255));
        homeBut.setBackground(new Color(102, 153, 255));
        historyBut.setForeground(Color.black);
        customerCheckInBut.setForeground(Color.WHITE);
        customerCheckOutBut.setForeground(Color.WHITE);
        homeBut.setForeground(Color.WHITE);
        manageRoomBut.setBackground(new Color(102, 153, 255));
        manageRoomBut.setForeground(Color.WHITE);
    }//GEN-LAST:event_historyButMouseClicked

    private void manageRoomButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageRoomButMouseClicked
        // TODO add your handling code here:
        manageRoomBut.setBackground(Color.WHITE);
        customerCheckInBut.setBackground(new Color(102, 153, 255));
        customerCheckOutBut.setBackground(new Color(102, 153, 255));
        homeBut.setBackground(new Color(102, 153, 255));
        manageRoomBut.setForeground(Color.black);
        customerCheckInBut.setForeground(Color.WHITE);
        customerCheckOutBut.setForeground(Color.WHITE);
        homeBut.setForeground(Color.WHITE);
        historyBut.setBackground(new Color(102, 153, 255));
        historyBut.setForeground(Color.WHITE);
    }//GEN-LAST:event_manageRoomButMouseClicked

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        // TODO add your handling code here:
        new Login_Register().setVisible(true);
        setVisible(false);
        new MainDashboard().dispose();


    }//GEN-LAST:event_logOutMouseClicked

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(Color.WHITE);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerCheckInBut;
    private javax.swing.JLabel customerCheckOutBut;
    private javax.swing.JLabel historyBut;
    private javax.swing.JLabel homeBut;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logOut;
    private javax.swing.JLabel manageRoomBut;
    private test.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
